name = "ScatteringTransforms"
uuid = "68b593e8-16bb-4169-afcb-087dab360691"
version = "0.1.0"
authors = ["Jordan Benjamin"]

[sources]
ComputationalBackends = { url = "https://github.com/jbphyswx/ComputationalBackends.jl" }
SpectralBackends = { url = "https://github.com/jbphyswx/SpectralBackends.jl" }

[deps]
ComputationalBackends = "5c6e2104-4040-447f-8fc0-66ec2223b019"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SpectralBackends = "289ded02-b044-41b2-8b2d-71f2a47755d1"

[weakdeps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FINUFFT = "d8beea63-0952-562e-9c6a-8e8ef7364055"
FastSphericalHarmonics = "d335c211-7587-445e-a753-f0b1fb7e445f"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
NUFSHT = "e99b67a3-9706-455a-90e2-85b195a33206"
NonuniformFFTs = "cd96f58b-6017-4a02-bb9e-f4d81626177f"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"

[extensions]
ScatteringTransformsCairoMakieExt = "CairoMakie"
ScatteringTransformscuFINUFFTExt = ["CUDA", "FINUFFT"]
ScatteringTransformsDifferentiationInterfaceExt = "DifferentiationInterface"
ScatteringTransformsDistributedExt = "Distributed"
ScatteringTransformsFFTWExt = "FFTW"
ScatteringTransformsFINUFFTExt = "FINUFFT"
ScatteringTransformsFastSphericalHarmonicsExt = "FastSphericalHarmonics"
ScatteringTransformsKernelAbstractionsExt = ["KernelAbstractions", "AbstractFFTs"]
ScatteringTransformsMPIExt = "MPI"
ScatteringTransformsNUFSHTExt = "NUFSHT"
ScatteringTransformsNonuniformFFTsExt = "NonuniformFFTs"
ScatteringTransformsOhMyThreadsExt = "OhMyThreads"

[compat]
AbstractFFTs = "1"
CUDA = "5, 6"
CairoMakie = "0.15"
ComputationalBackends = "0.1"
DifferentiationInterface = "0.7"
Distributed = "1"
FFTW = "1"
FINUFFT = "3.5.2"
FastSphericalHarmonics = "1"
KernelAbstractions = "0.9"
LinearAlgebra = "1"
MPI = "0.20"
NUFSHT = "0.1"
NonuniformFFTs = "0.9"
PrecompileTools = "1"
OhMyThreads = "0.7, 0.8"
SpectralBackends = "0.1"
julia = "1.11"

[workspace]
projects = ["test", "docs", "examples", "gpu"]

