[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ScatteringTransforms = "68b593e8-16bb-4169-afcb-087dab360691"

[sources]
ScatteringTransforms = { path = ".." }

[compat]
Documenter = "1"
julia = "1.11"
